#!/usr/bin/env tsx
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

import { createContactDefinition } from "../src/tools/create-contact.js";
import { deleteContactDefinition } from "../src/tools/delete-contact.js";
import { getContactDefinition } from "../src/tools/get-contact.js";
import { listAddressBooksDefinition } from "../src/tools/list-address-books.js";
import { listContactsDefinition } from "../src/tools/list-contacts.js";
import { updateContactDefinition } from "../src/tools/update-contact.js";

type ToolDefinition = {
	name: string;
	description: string;
	inputSchema: Record<string, z.ZodTypeAny>;
	returns?: string;
};

// Render order is significant: this is the order tools appear in the README.
const TOOLS: ToolDefinition[] = [
	listAddressBooksDefinition,
	listContactsDefinition,
	getContactDefinition,
	createContactDefinition,
	updateContactDefinition,
	deleteContactDefinition,
];

const START = "<!-- TOOLS:START - generated by scripts/gen-tool-docs.ts -->";
const END = "<!-- TOOLS:END -->";

function unwrapOptional(schema: z.ZodTypeAny): {
	inner: z.ZodTypeAny;
	optional: boolean;
} {
	if (schema instanceof z.ZodOptional) {
		return { inner: schema.unwrap() as z.ZodTypeAny, optional: true };
	}
	return { inner: schema, optional: false };
}

function describeType(schema: z.ZodTypeAny): string {
	if (schema instanceof z.ZodString) return "string";
	if (schema instanceof z.ZodNumber) return "number";
	if (schema instanceof z.ZodBoolean) return "boolean";
	if (schema instanceof z.ZodEnum) {
		const values = (schema as z.ZodEnum<[string, ...string[]]>).options;
		return `enum (${values.map((v) => `\`${v}\``).join(" | ")})`;
	}
	if (schema instanceof z.ZodArray) {
		const element = (schema as z.ZodArray<z.ZodTypeAny>).element;
		return `array of ${describeType(element)}`;
	}
	if (schema instanceof z.ZodObject) return "object";
	return "value";
}

function renderField(name: string, schema: z.ZodTypeAny, indent = ""): string {
	const { inner, optional } = unwrapOptional(schema);
	const description = (inner.description ?? schema.description) as
		| string
		| undefined;
	const typeLabel = describeType(inner);
	const optionalLabel = optional ? " (optional)" : "";
	const trailing = description ? ` — ${description}` : "";
	const head = `${indent}- \`${name}\`: ${typeLabel}${optionalLabel}${trailing}`;
	if (inner instanceof z.ZodObject) {
		const shape = (inner as z.ZodObject<Record<string, z.ZodTypeAny>>).shape;
		const children = Object.entries(shape)
			.map(([k, v]) => renderField(k, v, `${indent}  `))
			.join("\n");
		return children ? `${head}\n${children}` : head;
	}
	return head;
}

function renderTool(tool: ToolDefinition): string {
	const lines: string[] = [];
	lines.push(`### ${tool.name}`);
	lines.push("");
	lines.push(tool.description);
	lines.push("");
	const entries = Object.entries(tool.inputSchema);
	if (entries.length === 0) {
		lines.push("Parameters: none");
	} else {
		lines.push("Parameters:");
		for (const [name, schema] of entries) {
			lines.push(renderField(name, schema));
		}
	}
	if (tool.returns) {
		lines.push("");
		lines.push("Returns:");
		lines.push(`- ${tool.returns}`);
	}
	return lines.join("\n");
}

function renderAll(): string {
	return TOOLS.map(renderTool).join("\n\n");
}

function updateReadme(readmePath: string, body: string): string {
	const current = readFileSync(readmePath, "utf8");
	const block = `${START}\n${body}\n${END}`;
	if (!current.includes(START) || !current.includes(END)) {
		throw new Error(
			`README is missing ${START} / ${END} markers. Add them around the existing tool docs.`,
		);
	}
	const pattern = new RegExp(
		`${escapeRegex(START)}[\\s\\S]*?${escapeRegex(END)}`,
	);
	return current.replace(pattern, block);
}

function escapeRegex(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function main() {
	const here = dirname(fileURLToPath(import.meta.url));
	const readmePath = resolve(here, "..", "README.md");
	const check = process.argv.includes("--check");

	const next = updateReadme(readmePath, renderAll());
	const current = readFileSync(readmePath, "utf8");

	if (next === current) {
		if (!check) console.log("README tool docs already up to date.");
		return;
	}

	if (check) {
		console.error(
			"README tool docs are out of date. Run `npm run docs` and commit the result.",
		);
		process.exit(1);
	}

	writeFileSync(readmePath, next);
	console.log("README tool docs regenerated.");
}

main();
